### ISSUE TITLE
Funcionamento com angular 1.3

### ISSUE THREAD

**Issue by cezarpretto** [VictorQueiroz/ngCurrencyMask#9]
Alguma chance de um update para funcionar com angular 1.3? Esse componente é muito show... Mas com versões mais recentes do angular ele não funciona :(

**Comment by VictorQueiroz** [comment]
Qual problema? Coloque o que de fato acontece com alguma parte textual.

**Comment by cezarpretto** [comment]
Eu recebo um erro na hora de injetar o seu módulo no meu app.js. Segue o erro:

 Uncaught Error: [$injector:modulerr] Failed to instantiate module ncmhelperApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngCurrencyMask due to:
Error: [$injector:nomod] Module 'ngCurrencyMask' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.28/$injector/nomod?p0=ngCurrencyMask
    at VALIDITY_STATE_PROPERTY (http://0.0.0.0:9000/bower_components/angular/angular.js:78:12)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:1677:17
    at ensure (http://0.0.0.0:9000/bower_components/angular/angular.js:1601:38)
    at module (http://0.0.0.0:9000/bower_components/angular/angular.js:1675:14)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:3877:22
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:325:18)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:3871:5)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:3878:40
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:325:18)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:3871:5)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=ngCurrencyMask&p1=…A%2F%2F0.0.0.0%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A3871%3A5)
    at VALIDITY_STATE_PROPERTY (http://0.0.0.0:9000/bower_components/angular/angular.js:78:12)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:3905:15
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:325:18)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:3871:5)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:3878:40
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:325:18)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:3871:5)
    at createInjector (http://0.0.0.0:9000/bower_components/angular/angular.js:3811:11)
    at doBootstrap (http://0.0.0.0:9000/bower_components/angular/angular.js:1444:20)
    at bootstrap (http://0.0.0.0:9000/bower_components/angular/angular.js:1459:12)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=ncmhelperApp&p1=Er…%2F%2F0.0.0.0%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1459%3A12)

**Comment by VictorQueiroz** [comment]
Você não está usando Angular 1.3, e o problema provavelmente não é esse. Me mande mais partes do seu código para que eu possa identificar o causador do problema.

**Comment by cezarpretto** [comment]
Testei em um projeto novo.
Meu bower.json:

{
  "name": "controle-acesso",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.3.0",
    "json3": "^3.3.0",
    "es5-shim": "^4.0.0",
    "bootstrap": "^3.2.0",
    "angular-animate": "^1.3.0",
    "angular-cookies": "^1.3.0",
    "angular-messages": "^1.3.0",
    "angular-resource": "^1.3.0",
    "angular-route": "^1.3.0",
    "angular-sanitize": "^1.3.0",
    "angular-touch": "^1.3.0",
    "webcam-directive": "~2.0.0",
    "angular-camera": "~0.1.3",
    "angular-smart-table": "~2.0.1",
    "font-awesome": "~4.3.0",
    "angular-growl-v2": "~0.7.3",
    "angular-loading-bar": "~0.7.1",
    "angular-base64-upload": "~0.0.5",
    "angular-mask": "~3.0.11",
    "ng-currency-mask": "~1.0.61",
    "angular-i18n": "~1.3.14"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.0",
    "angular-scenario": "~1.3.0"
  },
  "overrides": {
    "angular-i18n": {
      "main": "angular-locale_pt-br.js"
    }
  },
  "appPath": "app"
}

E o erro retornado na hora de injetar ngCurrencyMask no app.js:

Uncaught Error: [$injector:modulerr] Failed to instantiate module controleAcessoApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngCurrencyMask due to:
Error: [$injector:nomod] Module 'ngCurrencyMask' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.14/$injector/nomod?p0=ngCurrencyMask
    at REGEX_STRING_REGEXP (http://0.0.0.0:9000/bower_components/angular/angular.js:63:12)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:1767:17
    at ensure (http://0.0.0.0:9000/bower_components/angular/angular.js:1691:38)
    at module (http://0.0.0.0:9000/bower_components/angular/angular.js:1765:14)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:4097:22
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:323:20)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:4081:5)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:4098:40
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:323:20)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:4081:5)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=ngCurrencyMask&p1=…A%2F%2F0.0.0.0%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (http://0.0.0.0:9000/bower_components/angular/angular.js:63:12)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:4120:15
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:323:20)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:4081:5)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:4098:40
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:323:20)
    at loadModules (http://0.0.0.0:9000/bower_components/angular/angular.js:4081:5)
    at createInjector (http://0.0.0.0:9000/bower_components/angular/angular.js:4007:11)
    at doBootstrap (http://0.0.0.0:9000/bower_components/angular/angular.js:1445:20)
    at bootstrap (http://0.0.0.0:9000/bower_components/angular/angular.js:1466:12)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=controleAcessoApp&…%2F%2F0.0.0.0%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1466%3A12)

**Comment by VictorQueiroz** [comment]
O problema claramente é por algum problema de carregamento do módulo que está acontecendo, verifique a ordem com que carregou suas dependências no HTML.
